- alias: "LED TEST"
  trigger: []

  action:
    - service: switch.turn_on
      target:
        entity_id: switch.kitchen_lights




- alias: "LED1 ON TEST"
  trigger:
    - platform: time
      at: "01:54:00"

  action:
    - service: switch.turn_on
      target:
        entity_id: switch.kitchen_lights

- alias: "LED SWITCH TEST"
  trigger:
    - platform: time
      at: "01:54:10"

  action:
    - service: switch.turn_off
      target:
        entity_id: switch.kitchen_lights

    - service: switch.turn_on
      target:
        entity_id: switch.bathroom_lights
